"""Node Object added

Revision ID: 1687d7371832
Revises: ac27f719e1f9
Create Date: 2020-01-13 16:30:23.676021

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '1687d7371832'
down_revision = 'ac27f719e1f9'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
