"""order_product associtation table fix

Revision ID: 27b4989f8ad5
Revises: 9327b873d98c
Create Date: 2020-01-23 19:51:54.273625

"""
from alembic import op
import sqlalchemy as sa
import backend
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27b4989f8ad5'
down_revision = '9327b873d98c'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'updated_at')
    op.drop_column('order_product', 'id')
    op.drop_column('order_product', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('order_product', sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('order_product', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
