"""Image.photo column changed to Image.path

Revision ID: 3b85ca0742b5
Revises: f1b545f34a48
Create Date: 2019-12-23 18:31:34.585976

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '3b85ca0742b5'
down_revision = 'f1b545f34a48'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('path', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'path')
    # ### end Alembic commands ###
