"""Image.tite and Image.slug removed

Revision ID: 5e7c3dea509b
Revises: 29e572cc53c3
Create Date: 2019-12-24 12:28:47.375543

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '5e7c3dea509b'
down_revision = '29e572cc53c3'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_image_title', 'image', type_='unique')
    op.drop_column('image', 'title')
    op.drop_column('image', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('slug', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('image', sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_image_title', 'image', ['title'])
    # ### end Alembic commands ###
