"""path column added to Order table

Revision ID: 790347a80ce5
Revises: 8996d6fe605d
Create Date: 2020-01-24 20:58:25.296214

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '790347a80ce5'
down_revision = '8996d6fe605d'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'path')
    # ### end Alembic commands ###
