"""Password and stripe id removed from stripe user

Revision ID: 8996d6fe605d
Revises: 27b4989f8ad5
Create Date: 2020-01-24 12:37:49.356993

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '8996d6fe605d'
down_revision = '27b4989f8ad5'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_user', 'password')
    op.drop_column('stripe_user', 'stripe_customer_id')
    op.drop_column('stripe_user', 'stripe_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_user', sa.Column('stripe_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('stripe_user', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('stripe_user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
