"""Node Object added

Revision ID: 8f8acde0ea4a
Revises: 1687d7371832
Create Date: 2020-01-13 16:34:51.353820

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import backend


# revision identifiers, used by Alembic.
revision = '8f8acde0ea4a'
down_revision = '1687d7371832'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node'))
    )
    op.create_index('ix_nodes_path', 'node', ['path'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nodes_path', table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
