"""Category and event added to photo models

Revision ID: ac27f719e1f9
Revises: 7f1c0274397e
Create Date: 2020-01-11 22:36:45.606740

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = 'ac27f719e1f9'
down_revision = '7f1c0274397e'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(name='is_public'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('event',
    sa.Column('id', sa.BigInteger().with_variant(sa.INTEGER(), 'sqlite'), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('is_public', sa.Boolean(name='is_public'), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_event_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.add_column('album', sa.Column('event_id', sa.BigInteger(), nullable=True))
    op.add_column('album', sa.Column('price', sa.Float(), nullable=True))
    op.create_foreign_key(op.f('fk_album_event_id_event'), 'album', 'event', ['event_id'], ['id'])
    op.add_column('image', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'price')
    op.drop_constraint(op.f('fk_album_event_id_event'), 'album', type_='foreignkey')
    op.drop_column('album', 'price')
    op.drop_column('album', 'event_id')
    op.drop_table('event')
    op.drop_table('category')
    # ### end Alembic commands ###
